replicaCount: 1

image:
  repository: chirag123456789/cbblogs
  tag: c988277f34057e25fbe78ba9d1bbd677628274cf
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

autoscaling:
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 80

mysql:
  enabled: true

  image:
    repository: mysql
    tag: "8.0"

  host: mysql
  port: 3306
  database: blogdb
  username: root
  password: ""
  rootPassword: ""
  persistence:
    enabled: true
    storageClass: standard
    size: 10Gi

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 1Gi

ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - host: chirag-blogs.cb.co
      paths:
        - path: /
          pathType: Prefix
  tls: []

serviceAccount:
  create: false
  name: ""
  annotations: {}
