{{- if .Values.mysql.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "cbblogs.fullname" . }}-mysql
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: openbao
    kind: SecretStore

  target:
    name: {{ include "cbblogs.fullname" . }}-mysql
    creationPolicy: Owner

  data:
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: secret/mysql
        property: MYSQL_ROOT_PASSWORD

    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: secret/mysql
        property: MYSQL_PASSWORD
{{- end }}