{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cbblogs.fullname" . }}-mysql
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword | quote }}
  MYSQL_PASSWORD: {{ .Values.mysql.password | quote }}
{{- end }}