apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: openbao
  namespace: cbblogs

spec:
  provider:
    vault:
      server: "server: http://openbao.default.svc.cluster.local:8200"
      path: "secret"
      version: "v2"

      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "cbblogs"

          serviceAccountRef:
            name: "cbblogs"