name: SAST (Static Application Security Testing)

on:
  workflow_run:
    workflows: ["linting"]
    types:
      - completed

jobs:
  semgrep-sast:
    name: Semgrep Code Scan
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Run Semgrep SAST
        uses: semgrep/semgrep-action@v1
        with:
          config: p/security-audit 
          failOn: 'error' 
          failOn: 'warning'

      - name: Upload SARIF results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
        if: always() # Ensures the scan report uploads even if vulnerabilities are found
